### ISSUE TITLE
support local dependencies / monorepos

### ISSUE THREAD

**Issue by cdepillabout** [cdepillabout/purescript2nix#7]
Spago [provides a way](https://github.com/purescript/spago#monorepo) to develop multiple PureScript packages all living in the same repo, using the same package set.

`purescript2nix` doesn't currently have support for this, but I imagine it wouldn't be too hard to add.

**Comment by considerate** [comment]
This issue can now be simplified to supporting `subdir` in `extra_packages`. It's unclear what the proposed yaml format for that would be, however.
